use colored::*;
use std::fs;
use std::path::Path;
use crate::project;

pub fn execute(package: Option<&str>, license: Option<&str>) {
    let modules_dir = Path::new("srishti_modules");
    if !modules_dir.exists() {
        fs::create_dir(modules_dir).expect("Failed to create srishti_modules directory");
    }

    if let Some(pkg) = package {
        println!("{} Resolving {} from registry.srishti.dev...", "[INSTALL]".green().bold(), pkg);
        
        if let Some(key) = license {
            println!("  Authenticating with premium license key: {}***", &key[..std::cmp::min(4, key.len())]);
            println!("  {} License verified. Downloading premium agent...", "[SUCCESS]".green());
        } else {
            println!("  {} Downloading open-source agent...", "[SUCCESS]".green());
        }
        
        let local_pkg = Path::new("target").join(format!("{}.tar.gz", pkg));
        if local_pkg.exists() {
            println!("  {} Extracting from local cache/registry...", "[UNPACK]".cyan());
            let content = fs::read_to_string(&local_pkg).unwrap_or_default();
            fs::write(modules_dir.join(format!("{}.srishti", pkg)), content).unwrap();
        } else {
            let dummy_content = format!("// Package: {}\n", pkg);
            fs::write(modules_dir.join(format!("{}.srishti", pkg)), dummy_content).unwrap();
        }
        
        println!("{} Installed {} to srishti_modules/", "[DONE]".green().bold(), pkg);
    } else {
        println!("{} dependencies from srishti.toml...", "Installing".green().bold());
        
        if let Some(proj) = project::load_project() {
            // Simulated dependencies
            println!("{} Found project: {}", "Loaded".cyan(), proj.project.name);
            println!("{} Resolving dependencies...", "Resolving".cyan());
            
            // In a real implementation we would iterate over proj.dependencies
            // Since we mocked dependencies for now, we'll just print success
            println!("{} All dependencies are up to date.", "Success".green().bold());
        } else {
            eprintln!("{} Could not find or parse srishti.toml. Are you in a Srishti project?", "Error".red().bold());
        }
    }

    // Generate a dummy lockfile
    let lock_content = "# Auto-generated by srishti install\nversion = \"0.1.0\"\n";
    fs::write("srishti.lock", lock_content).unwrap_or_default();
}
