use crate::ast::*;

pub struct Codegen;

impl Codegen {
    pub fn new() -> Self {
        Self
    }
    
    pub fn generate(&self, program: &Program) -> String {
        let mut out = String::new();
        out.push_str("// Auto-generated by Srishti Compiler\n");
        out.push_str("use srishti_runtime::*;\n\n");
        
        for agent in &program.agents {
            out.push_str(&format!("pub struct {} {{\n", agent.name));
            out.push_str("    pub semantic_engine: SemanticEngine,\n");
            
            for mem in &agent.persistent_memory {
                if let Statement::LetDecl { name, .. } = mem {
                    out.push_str(&format!("    pub {}: VectorMemory,\n", name));
                }
            }
            out.push_str("}\n\n");
            
            out.push_str(&format!("impl {} {{\n", agent.name));
            
            // generate intents
            for intent in &agent.intents {
                out.push_str(&format!("    pub async fn {}(&self) -> Result<(), anyhow::Error> {{\n", intent.name));
                out.push_str("        // ... achieved via semantic engine ...\n");
                out.push_str("        Ok(())\n");
                out.push_str("    }\n");
            }
            
            out.push_str("}\n");
        }
        
        out
    }
}
