use crate::ast::*;

pub struct Codegen;

impl Codegen {
    pub fn new() -> Self {
        Self
    }

    pub fn generate(&self, program: &Program) -> String {
        let mut out = String::new();
        out.push_str("// Auto-generated by Srishti Compiler\n");
        out.push_str("#![allow(unused_variables)]\n");
        out.push_str("use srishti_runtime::*;\n");
        out.push_str("use std::collections::HashMap;\n\n");

        for agent in &program.agents {
            out.push_str(&format!("pub struct {} {{\n", agent.name));
            out.push_str("    pub semantic_engine: SemanticEngine,\n");
            for mem in &agent.memories {
                out.push_str(&format!("    pub {}: VectorMemory,\n", mem.name));
            }
            out.push_str("}\n\n");

            out.push_str(&format!("impl {} {{\n", agent.name));
            out.push_str("    pub fn new(api_key: String, provider: String) -> Self {\n");
            out.push_str("        Self {\n");
            out.push_str("            semantic_engine: SemanticEngine::new(api_key, provider),\n");
            for mem in &agent.memories {
                out.push_str(&format!(
                    "            {}: VectorMemory::new(\"{}_{}\"),\n",
                    mem.name, agent.name, mem.name
                ));
            }
            out.push_str("        }\n");
            out.push_str("    }\n\n");

            // guardrails
            for gr in &agent.guardrails {
                let _args_str: Vec<String> = gr
                    .args
                    .iter()
                    .map(|a| format!("{}: {:?}", a.name, a.typ))
                    .collect();
                // for MVP let's just make args f64 for Float etc
                let typed_args: Vec<String> = gr
                    .args
                    .iter()
                    .map(|a| {
                        let rtyp = match a.typ {
                            Type::Float => "f64",
                            Type::String => "String",
                            Type::Boolean => "bool",
                            Type::Integer => "i64",
                            Type::Custom(_) => "Value",
                        };
                        format!("{}: {}", a.name, rtyp)
                    })
                    .collect();

                out.push_str(&format!(
                    "    pub fn guardrail_{}(&self, {}) -> Result<(), String> {{\n",
                    gr.name,
                    typed_args.join(", ")
                ));
                for stmt in &gr.body {
                    if let Statement::Assert {
                        condition,
                        else_action,
                    } = stmt
                    {
                        let cond_str = self.gen_expr(condition);
                        out.push_str(&format!("        if !({}) {{\n", cond_str));
                        if let Some(action) = else_action {
                            out.push_str(&format!(
                                "            return Err(\"{}\".to_string());\n",
                                action
                            ));
                        } else {
                            out.push_str(&format!(
                                "            return Err(\"Guardrail {} failed\".to_string());\n",
                                gr.name
                            ));
                        }
                        out.push_str("        }\n");
                    }
                }
                out.push_str("        Ok(())\n");
                out.push_str("    }\n\n");
            }

            // tools
            for tool in &agent.tools {
                let typed_args: Vec<String> = tool
                    .args
                    .iter()
                    .map(|a| {
                        let rtyp = match a.typ {
                            Type::Float => "f64",
                            Type::String => "String",
                            Type::Boolean => "bool",
                            Type::Integer => "i64",
                            Type::Custom(_) => "Value",
                        };
                        format!("{}: {}", a.name, rtyp)
                    })
                    .collect();
                out.push_str(&format!(
                    "    pub async fn tool_{}(&self, {}) {{\n",
                    tool.name,
                    typed_args.join(", ")
                ));
                out.push_str(&format!(
                    "        println!(\"Executing tool {}\");\n",
                    tool.name
                ));
                out.push_str("    }\n\n");
            }

            // intents
            for intent in &agent.intents {
                out.push_str(&format!(
                    "    pub async fn intent_{}(&self) -> Result<(), anyhow::Error> {{\n",
                    intent.name
                ));
                for stmt in &intent.body {
                    if let Statement::Achieve { goal } = stmt {
                        out.push_str(&format!("        let _ = self.semantic_engine.achieve(\"{}\", &HashMap::new()).await?;\n", goal));
                    }
                }
                out.push_str("        Ok(())\n");
                out.push_str("    }\n");
            }

            out.push_str("}\n");
        }

        out
    }

    fn gen_expr(&self, expr: &Expression) -> String {
        match expr {
            Expression::Variable(v) => v.clone(),
            Expression::LiteralFloat(f) => format!("{}_f64", f),
            Expression::LiteralInt(i) => format!("{}", i),
            Expression::LiteralString(s) => format!("\"{}\".to_string()", s),
            Expression::BooleanLiteral(b) => format!("{}", b),
            Expression::BinaryOp { left, op, right } => {
                format!("{} {} {}", self.gen_expr(left), op, self.gen_expr(right))
            }
            Expression::MethodCall { object, method, args } => {
                let args_str: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
                format!("{}.{}({})", self.gen_expr(object), method, args_str.join(", "))
            }
            Expression::FieldAccess { object, field } => {
                format!("{}.{}", self.gen_expr(object), field)
            }
        }
    }
}

impl Default for Codegen {
    fn default() -> Self {
        Self::new()
    }
}
